#!/bin/bash
# openshift error check
/bin/oc get nodes > /root/oseoutput
chmod 755 /root/oseoutput
var1=$(tr -s ' ' '\n' </root/oseoutput| grep -c 'Ready')
# Checks if openshift installed correctly or not
if [ $var1 -ne 3 ];then
   echo "Openshift didn't Installed correctly and reinstalling again"
   #ssh -C -tt -v -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ose-master.rhosepaas.com /bin/ansible-playbook /root/openshift-ansible/playbooks/byo/config.yml > /tmp/ose_install.2.log
   ssh -C -tt -v -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ose-master.rhosepaas.com /bin/ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml > /tmp/ose_install.2.log
  /bin/sed -i "s/name: deny_all/name: my_htpasswd_provider/g" /etc/openshift/master/master-config.yaml
  /bin/sed -i "/kind: DenyAllPasswordIdentityProvider/a \     \ file: /etc/openshift/master/users.htpasswd" /etc/openshift/master/master-config.yaml
  /bin/sed -i "s/kind: DenyAllPasswordIdentityProvider/kind: HTPasswdPasswordIdentityProvider/g" /etc/openshift/master/master-config.yaml
  yum -y install httpd-tools
  useradd ose_user; htpasswd -c -b /etc/openshift/master/users.htpasswd ose_user redhat
  systemctl restart openshift-master
fi

var3=0
/bin/oc get nodes > /root/oseoutput
var2=$(tr -s ' ' '\n' </root/oseoutput| grep -c 'Ready')
while [ $var2 -ne 3 ]; do
    sleep 30
	 echo "Checking openshift Installation -- $var3 loop"
	 var3=$((var3+1))
	/bin/oc get nodes > /root/oseoutput
    var2=$(tr -s ' ' '\n' </root/oseoutput| grep -c 'Ready')
done

if [ $var2 -eq 3 ];then
   echo "Openshift Installed Successfully"
else
   echo "Installation Failed"  
fi

oadm registry --config=/etc/openshift/master/admin.kubeconfig --credentials=/etc/openshift/master/openshift-registry.kubeconfig --images='registry.access.redhat.com/openshift3/ose-${component}:${version}'
sleep 10
echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router2"}}' | oc create -f -
sleep 10
oc get scc privileged -o json | jq '.users |= .- ["system:serviceaccount:default:router"]' | oc replace scc -f -
oc get scc privileged -o json | jq '.users |= .+ ["system:serviceaccount:default:router2","ose_user"]' | oc replace scc -f -
sleep 3
oc label node ose-node1.rhosepaas.com region=infra zone=default
sleep 20
oadm router ose-master --credentials='/etc/openshift/master/openshift-router.kubeconfig' --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --service-account=router2 --selector='region=infra'
sleep 60
/bin/oc get pods
echo "checking pods"
cmd=`/bin/oc get pods | wc -l`
if [ $cmd -le 2 ] ; then
  echo "COMPLETETION FAILED"
else
 echo "COMPLETED SUCCUSSFULLY !!!"
fi

